### ISSUE TITLE
an alternative ;)

### ISSUE THREAD

**Issue by vitaly-t** [numtel/progress-promise#1]
Most of what you do here is implemented within the [spex](https://github.com/vitaly-t/spex) library. All its methods provide notification callbacks that can be used for tracking progress, among other things ;)

**Comment by jamesamcl** [comment]
And many people like libraries that do one thing and do it well.  A bit rich to plug your own library by opening an issue on another one.

**Comment by vitaly-t** [comment]
> A bit rich to plug your own library by opening an issue on another one.

A bit low to scorn someone's free help offer.
